[package]
name = "rust-metasploit"
version = "0.1.0"
authors = ["h4ck3r@parrot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="0.9.15"
rmp="*"
rmp-serde="0.13.7"
serde={ version="1.0.90" , features=["derive"]}
