name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo b --example auth
      run: cargo b --example console
      run: cargo b --example core
      run: cargo b --example jobs
      run: cargo b --example modules
      run: cargo b --example plugins
      run: cargo b --example sessions
